// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/flipcloud-ai/ezauth",
        "contact": {
            "name": "EzAuth Maintainers",
            "url": "https://github.com/flipcloud-ai/ezauth"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ezauth/callback": {
            "get": {
                "description": "Completes the OAuth2 authorization flow. The IdP redirects the browser here with authorization code and state. On success the user gets a session cookie and is redirected to the app. In auth-only mode returns 200 JSON.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "OAuth2/OIDC callback handler",
                "parameters": [
                    {
                        "type": "string",
                        "description": "State parameter for CSRF protection",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization code (authorization code flow)",
                        "name": "code",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Auth-only mode success JSON",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "302": {
                        "description": "Redirect to app (proxy mode)"
                    },
                    "400": {
                        "description": "Callback processing error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/groups/": {
            "get": {
                "description": "Returns a paginated list of all groups.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group Management"
                ],
                "summary": "List groups",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page size (default 30)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Group list",
                        "schema": {
                            "$ref": "#/definitions/dto.GroupListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid pagination params",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new group with the specified name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group Management"
                ],
                "summary": "Create a group",
                "parameters": [
                    {
                        "description": "Group name",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Group created"
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Duplicate group name",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/groups/{name}": {
            "get": {
                "description": "Returns group details including member users and assigned roles.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group Management"
                ],
                "summary": "Get a group by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Group details",
                        "schema": {
                            "$ref": "#/definitions/dto.GroupResponse"
                        }
                    },
                    "404": {
                        "description": "Group not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Renames an existing group.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group Management"
                ],
                "summary": "Update a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Current group name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New group name",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Group updated"
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Group not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Permanently removes a group from the database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group Management"
                ],
                "summary": "Delete a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group name to delete",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Group deleted"
                    },
                    "404": {
                        "description": "Group not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/groups/{name}/members/assign": {
            "post": {
                "description": "Assigns one or more users to a group.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group Management"
                ],
                "summary": "Add members to a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User IDs to add",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GroupMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Members added"
                    },
                    "400": {
                        "description": "Missing parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Group or user not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/groups/{name}/members/unassign": {
            "delete": {
                "description": "Removes one or more users from a group.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group Management"
                ],
                "summary": "Remove members from a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User IDs to remove",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GroupMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Members removed"
                    },
                    "400": {
                        "description": "Missing parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Group or user not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/groups/{name}/roles/assign": {
            "post": {
                "description": "Grants roles to a group. All group members inherit these roles.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group Management"
                ],
                "summary": "Assign roles to a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Roles to assign",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GroupRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Roles assigned"
                    },
                    "400": {
                        "description": "Missing parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Group or role not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/groups/{name}/roles/unassign": {
            "delete": {
                "description": "Revokes roles from a group.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group Management"
                ],
                "summary": "Unassign roles from a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Roles to unassign",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GroupRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Roles unassigned"
                    },
                    "400": {
                        "description": "Missing parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Group or role not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/login": {
            "get": {
                "description": "GET returns the HTML login page with provider buttons and username/password form. POST authenticates with username/password and creates a session cookie. In proxy mode the client is redirected to the upstream; in auth-only mode a 200 JSON/HTML success is returned.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html",
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Authenticate user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username (required for POST auth)",
                        "name": "username",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Password (required for POST auth)",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Redirect target after successful login",
                        "name": "redirect",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login page HTML (GET) or success (auth-only POST)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "302": {
                        "description": "Redirect to upstream (proxy mode POST)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "GET returns the HTML login page with provider buttons and username/password form. POST authenticates with username/password and creates a session cookie. In proxy mode the client is redirected to the upstream; in auth-only mode a 200 JSON/HTML success is returned.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html",
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Authenticate user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username (required for POST auth)",
                        "name": "username",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Password (required for POST auth)",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Redirect target after successful login",
                        "name": "redirect",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login page HTML (GET) or success (auth-only POST)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "302": {
                        "description": "Redirect to upstream (proxy mode POST)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/logout": {
            "get": {
                "description": "Invalidates the session and clears the session cookie. For OIDC sessions, attempts RFC 7009 upstream token revocation (best-effort). Returns 204 to API clients and redirects browsers to the login page.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Log out and clear session",
                "responses": {
                    "204": {
                        "description": "Session cleared successfully (API clients)"
                    },
                    "302": {
                        "description": "Redirect to login page (browsers)"
                    },
                    "500": {
                        "description": "Failed to clear session",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Invalidates the session and clears the session cookie. For OIDC sessions, attempts RFC 7009 upstream token revocation (best-effort). Returns 204 to API clients and redirects browsers to the login page.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Log out and clear session",
                "responses": {
                    "204": {
                        "description": "Session cleared successfully (API clients)"
                    },
                    "302": {
                        "description": "Redirect to login page (browsers)"
                    },
                    "500": {
                        "description": "Failed to clear session",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/me": {
            "get": {
                "description": "Returns the profile of the currently authenticated user. For OIDC users the profile is built from the session; for DB users it is fetched from the database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Self-Service"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "User profile",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database not available or user not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/me/tokens": {
            "get": {
                "description": "Returns metadata for all PATs belonging to the currently authenticated user. Token values are never returned.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Self-Service"
                ],
                "summary": "List my personal access tokens",
                "responses": {
                    "200": {
                        "description": "Token list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.PATListItem"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database not available",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Generates a new opaque token for the currently authenticated user. OIDC users cannot create PATs. The plaintext token is returned once and never stored.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Self-Service"
                ],
                "summary": "Create a personal access token",
                "parameters": [
                    {
                        "description": "Token creation request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePATRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Token created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePATResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or OIDC user",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database not available",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/me/tokens/{id}": {
            "delete": {
                "description": "Permanently deletes the specified token. The operation is irreversible.",
                "tags": [
                    "Self-Service"
                ],
                "summary": "Revoke a personal access token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token revoked"
                    },
                    "400": {
                        "description": "Missing token ID",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Token or database not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/provider/": {
            "get": {
                "description": "Returns all OIDC/OAuth2 provider configurations from the database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider Management"
                ],
                "summary": "List providers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Max results (default 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Provider list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ProviderDB"
                            }
                        }
                    },
                    "404": {
                        "description": "Database not available",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a new OIDC/OAuth2 provider configuration to the database.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider Management"
                ],
                "summary": "Create a provider",
                "parameters": [
                    {
                        "description": "Provider configuration",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ProviderDB"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Provider created"
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflicts with a static provider",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/provider/{name}": {
            "get": {
                "description": "Returns the OIDC/OAuth2 provider configuration.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider Management"
                ],
                "summary": "Get a provider by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Provider configuration",
                        "schema": {
                            "$ref": "#/definitions/config.ProviderConfig"
                        }
                    },
                    "404": {
                        "description": "Provider not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing OIDC/OAuth2 provider configuration in the database. The provider name is fixed and cannot be changed via this API.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider Management"
                ],
                "summary": "Update a provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated provider fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateProviderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Provider updated"
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Provider not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflicts with a static provider",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes an OIDC/OAuth2 provider from the database and clears it from the cache.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider Management"
                ],
                "summary": "Delete a provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider name to delete",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Provider deleted"
                    },
                    "404": {
                        "description": "Provider not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/start": {
            "get": {
                "description": "Redirects the browser to the identity provider's authorization URL for the specified provider. If no provider query param is given, renders the login page with an error.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Start OAuth2/OIDC login flow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider name to use for authentication",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to IdP authorization URL"
                    },
                    "400": {
                        "description": "No provider found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get login URL",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/users/": {
            "get": {
                "description": "Returns a paginated list of all users.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "List users",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page size (default 30)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (1-based, alternative to offset)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of users",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.UserListItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid pagination params",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates profile fields for an existing user. The body must include the user ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Update a user",
                "parameters": [
                    {
                        "description": "Updated user fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User updated"
                    },
                    "400": {
                        "description": "Invalid request body or user ID",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new user with the specified profile fields and password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Create a user",
                "parameters": [
                    {
                        "description": "User details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User created"
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Duplicate username/email",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Permanently removes a user from the database. The body must include the user ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "description": "User ID to delete",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User deleted"
                    },
                    "400": {
                        "description": "Missing user ID",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/users/{uid}": {
            "get": {
                "description": "Returns the full profile for a single user, including roles and groups.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Get a user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User profile",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/users/{uid}/reset-password": {
            "put": {
                "description": "Sets a new password for the specified user. Requires admin privileges.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Reset a user's password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password changed"
                    },
                    "400": {
                        "description": "Missing user ID or password",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/users/{uid}/roles/assign": {
            "post": {
                "description": "Grants the specified roles to a user. Roles are referenced by name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Assign roles to a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Roles to assign",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Roles assigned"
                    },
                    "400": {
                        "description": "Missing parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User or role not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/users/{uid}/roles/unassign": {
            "delete": {
                "description": "Revokes the specified roles from a user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Management"
                ],
                "summary": "Unassign roles from a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Roles to unassign",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Roles unassigned"
                    },
                    "400": {
                        "description": "Missing parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User or role not found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ezauth/verify": {
            "get": {
                "description": "Returns the session status as JSON for external gateway auth_request integration (nginx, Kong, Envoy). 200 with user profile when authenticated; 401 when not. Never returns HTML or redirect.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Verify session (gateway auth_request integration)",
                "responses": {
                    "200": {
                        "description": "Authenticated: returns user, subject, email, groups, id_type",
                        "schema": {
                            "$ref": "#/definitions/dto.VerifyResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthenticated: returns {authenticated: false, error: ...}",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns 200 OK with a plain-text message indicating the service is healthy.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "XW Proxy is Healthy",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/robots.txt": {
            "get": {
                "description": "Returns the robots.txt file for web crawler directives.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Robots.txt",
                "responses": {
                    "200": {
                        "description": "Robots.txt content",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config.ProviderConfig": {
            "type": "object",
            "properties": {
                "admin_group": {
                    "type": "string"
                },
                "allowed_groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "claim_from_profile": {
                    "type": "boolean"
                },
                "client_id": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "device_auth_url": {
                    "$ref": "#/definitions/url.URL"
                },
                "enabled": {
                    "type": "boolean"
                },
                "login_parameters": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "provider_name": {
                    "type": "string"
                },
                "redirect_allowed_domains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "redirect_url": {
                    "$ref": "#/definitions/url.URL"
                },
                "scopes": {
                    "type": "string"
                },
                "skip_nonce": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string",
                    "default": "oauth2"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_claim": {
                    "type": "string"
                },
                "validate_url": {
                    "$ref": "#/definitions/url.URL"
                }
            }
        },
        "datatypes.URL": {
            "type": "object",
            "properties": {
                "forceQuery": {
                    "description": "append a query ('?') even if RawQuery is empty",
                    "type": "boolean"
                },
                "fragment": {
                    "description": "fragment for references, without '#'",
                    "type": "string"
                },
                "host": {
                    "description": "host or host:port (see Hostname and Port methods)",
                    "type": "string"
                },
                "omitHost": {
                    "description": "do not emit empty host (authority)",
                    "type": "boolean"
                },
                "opaque": {
                    "description": "encoded opaque data",
                    "type": "string"
                },
                "path": {
                    "description": "path (relative paths may omit leading slash)",
                    "type": "string"
                },
                "rawFragment": {
                    "description": "encoded fragment hint (see EscapedFragment method)",
                    "type": "string"
                },
                "rawPath": {
                    "description": "encoded path hint (see EscapedPath method)",
                    "type": "string"
                },
                "rawQuery": {
                    "description": "encoded query values, without '?'",
                    "type": "string"
                },
                "scheme": {
                    "type": "string"
                },
                "user": {
                    "description": "username and password information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/url.Userinfo"
                        }
                    ]
                }
            }
        },
        "dto.CreateGroupRequest": {
            "description": "Request body for creating a group. The name field is required.",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.CreatePATRequest": {
            "description": "Token creation request. expires_at is required and must be within 365 days from now.",
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-12-31T23:59:59Z"
                },
                "name": {
                    "type": "string",
                    "example": "ci-pipeline"
                }
            }
        },
        "dto.CreatePATResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.CreateUserRequest": {
            "description": "Request body for creating a user. Username and password are required; all other fields are optional (email is strongly recommended).",
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/models.AddressDB"
                },
                "birth_date": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "mobile_number": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.DeleteUserRequest": {
            "description": "Request body for deleting a user. The id field is required.",
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "description": "Unified error response with numeric code and human-readable message.",
            "type": "object",
            "properties": {
                "authenticated": {
                    "type": "boolean"
                },
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "dto.GroupListItem": {
            "description": "Summary row for a group in list views. Includes id and name.",
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.GroupListResponse": {
            "description": "Paginated list of groups with offset, limit, and total count metadata.",
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GroupListItem"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.GroupMemberRequest": {
            "description": "Request body for managing group membership. The users field is a list of user UUIDs.",
            "type": "object",
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.GroupResponse": {
            "description": "Full group details including member users, assigned roles, and creation timestamp.",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GroupUserItem"
                    }
                }
            }
        },
        "dto.GroupRoleRequest": {
            "description": "Request body for granting or revoking group roles. The roles field is a list of role names.",
            "type": "object",
            "properties": {
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.GroupUserItem": {
            "description": "Minimal user reference returned inside group details. Contains id and username.",
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.PATListItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_used_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.ResetPasswordRequest": {
            "description": "Request body for changing a user's password. The password field is required.",
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateGroupRequest": {
            "description": "Request body for updating a group. The name field is the new group name.",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateProviderRequest": {
            "description": "Request body for updating a provider configuration. All fields are optional; only provided fields are updated. provider_name and type cannot be changed via this API.",
            "type": "object",
            "properties": {
                "admin_group": {
                    "type": "string"
                },
                "allowed_groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "authorization_endpoint": {
                    "type": "string"
                },
                "claims_from_profile": {
                    "type": "boolean"
                },
                "client_id": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                },
                "code_challenge_methods_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "device_auth_url": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id_token_signing_alg_values_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "issuer": {
                    "type": "string"
                },
                "jwks_uri": {
                    "type": "string"
                },
                "login_parameters": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "protected_resource": {
                    "type": "string"
                },
                "redirect_url": {
                    "type": "string"
                },
                "revocation_endpoint": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "skip_nonce": {
                    "type": "boolean"
                },
                "token_endpoint": {
                    "type": "string"
                },
                "user_claim": {
                    "type": "string"
                },
                "userinfo_endpoint": {
                    "type": "string"
                },
                "validate_url": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateUserRequest": {
            "description": "Request body for updating a user. The id field is required; all other fields are optional and only provided fields are updated.",
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/models.AddressDB"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "mobile_number": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.UserListItem": {
            "description": "Summary row for a user in list views. Includes the most relevant fields for browsing users.",
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "country": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "last_login": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "mobile_number": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.UserResponse": {
            "description": "Full user profile including roles, groups, and address details.",
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "address": {
                    "$ref": "#/definitions/models.AddressDB"
                },
                "birth_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "id_type": {
                    "type": "string"
                },
                "last_login": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "mobile_number": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.UserRoleRequest": {
            "description": "Request body for granting or revoking roles. The roles field is a list of role names.",
            "type": "object",
            "properties": {
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.VerifyResponse": {
            "type": "object",
            "properties": {
                "authenticated": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id_type": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "models.AddressDB": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "zip_code": {
                    "type": "string"
                }
            }
        },
        "models.LoginParameters": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        },
        "models.ProviderDB": {
            "type": "object",
            "properties": {
                "admin_group": {
                    "type": "string"
                },
                "allowed_groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "authorization_endpoint": {
                    "$ref": "#/definitions/datatypes.URL"
                },
                "claims_from_profile": {
                    "type": "boolean"
                },
                "client_id": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                },
                "code_challenge_methods_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "device_auth_url": {
                    "$ref": "#/definitions/datatypes.URL"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id_token_signing_alg_values_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "issuer": {
                    "$ref": "#/definitions/datatypes.URL"
                },
                "jwks_uri": {
                    "$ref": "#/definitions/datatypes.URL"
                },
                "login_parameters": {
                    "$ref": "#/definitions/models.LoginParameters"
                },
                "protected_resource": {
                    "$ref": "#/definitions/datatypes.URL"
                },
                "provider_name": {
                    "type": "string"
                },
                "redirect_url": {
                    "$ref": "#/definitions/datatypes.URL"
                },
                "revocation_endpoint": {
                    "$ref": "#/definitions/datatypes.URL"
                },
                "scope": {
                    "type": "string"
                },
                "skip_nonce": {
                    "type": "boolean"
                },
                "token_endpoint": {
                    "$ref": "#/definitions/datatypes.URL"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_claim": {
                    "type": "string"
                },
                "userinfo_endpoint": {
                    "$ref": "#/definitions/datatypes.URL"
                },
                "validate_url": {
                    "$ref": "#/definitions/datatypes.URL"
                }
            }
        },
        "url.URL": {
            "type": "object",
            "properties": {
                "forceQuery": {
                    "description": "append a query ('?') even if RawQuery is empty",
                    "type": "boolean"
                },
                "fragment": {
                    "description": "fragment for references, without '#'",
                    "type": "string"
                },
                "host": {
                    "description": "host or host:port (see Hostname and Port methods)",
                    "type": "string"
                },
                "omitHost": {
                    "description": "do not emit empty host (authority)",
                    "type": "boolean"
                },
                "opaque": {
                    "description": "encoded opaque data",
                    "type": "string"
                },
                "path": {
                    "description": "path (relative paths may omit leading slash)",
                    "type": "string"
                },
                "rawFragment": {
                    "description": "encoded fragment hint (see EscapedFragment method)",
                    "type": "string"
                },
                "rawPath": {
                    "description": "encoded path hint (see EscapedPath method)",
                    "type": "string"
                },
                "rawQuery": {
                    "description": "encoded query values, without '?'",
                    "type": "string"
                },
                "scheme": {
                    "type": "string"
                },
                "user": {
                    "description": "username and password information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/url.Userinfo"
                        }
                    ]
                }
            }
        },
        "url.Userinfo": {
            "type": "object"
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT bearer token obtained from a successful login. Prefix with \"Bearer \".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "CookieAuth": {
            "description": "Session cookie set after login. Used by browser-based clients.",
            "type": "apiKey",
            "name": "_xw_session",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "EzAuth API",
	Description:      "OAuth2 / OIDC authentication reverse proxy. Supports username/password login, OIDC provider federation, session management, and admin CRUD for users, groups, providers, and RBAC.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
